In [1]:
import numpy as np

In [2]:
A = np.random.random([3, 4])

In [3]:
A

array([[0.87504576, 0.17742965, 0.44636495, 0.32856595],
       [0.42438998, 0.72650117, 0.51486054, 0.23064623],
       [0.51987938, 0.74789486, 0.01320389, 0.9631441 ]])

In [5]:
A + A

array([[1.75009153, 0.3548593 , 0.89272989, 0.65713191],
       [0.84877995, 1.45300234, 1.02972107, 0.46129245],
       [1.03975875, 1.49578971, 0.02640778, 1.9262882 ]])

In [6]:
np.linalg.norm(A)

1.9718051756007864

In [12]:
A = np.random.random([2, 1])
A.transpose()

array([[0.52136244, 0.91188349]])

In [14]:
np.matmul(A.transpose(), A, )

array([[1.10335029]])

In [15]:
z = np.matmul(A.transpose(), A)
np.tanh(z)

array([[0.80169923]])

In [16]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    if x < y:
        return x*y
    else:
        return x/y

In [19]:
A

array([[0.52136244],
       [0.91188349]])

In [18]:
np.vectorize(scalar_function(A, A))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [20]:
np.vectorize(scalar_function)(A,A)

array([[1.],
       [1.]])